### ISSUE TITLE
Links to previous editions

### ISSUE THREAD

**Issue by sourabhlal** [LauzHack/LauzHack.github.io#14]
Currently one can't see that its possible to see last years website, or the one before that. (unless you have the url) would be nice to have links from the current homepage.

**Comment by ebezzam** [comment]
This might fall in the same category; can we indicate on the website which companies have previously sponsored us?

For example, at the bottom of [this page](https://jacobshack.com/).

**Comment by sourabhlal** [comment]
@ebezzam perhaps we could, but we need to make them very small (I think StartHack did something similar last year). The focus should be on current sponsors.

**Comment by SolalPirelli** [comment]
Done. We can have the discussion about past sponsors on Slack.
