### ISSUE TITLE
Refactor website for newsletter + LauzHack Days

### ISSUE THREAD

**Issue by SolalPirelli** [LauzHack/LauzHack.github.io#16]
The website is currently focused on the main event, with:
- a header containing the date, social media, and a call to action
- a description of the main event and links to its past editions
- a FAQ for the event
- the list of sponsors of the event
- the committee
- a separate "legal" page for the boring stuff we must have on the website

Now that we have a newsletter and that we organize LauzHack Days, we need to add information about both of these. The question is how to do so while keeping the main page focused. We must also clearly separate potential sponsors for LauzHack Days from the main event sponsors.

One question that stands out is what the newsletter will be used for. If it's just for LauzHack Days, it can be only on the page for LauzHack Days; otherwise, it has to be on the main page, but would that mean spam for people outside of EPFL who can't come to LHDs?

Ideas welcome...

**Comment by ZofiaBlacktea** [comment]
To me it makes the most sense to add the info about the newsletter in the header next to all the social media stuff.

Did we decide to have the LHDs page be located at, for example, days.lauzhack.com? If so maybe add a small section after the description of LH explaining what LHDs are, with a link to that page? This way we can have the LHDs sponsors on that page and they'll be clearly separated from the main event sponsors. If the newsletter is only for LHDs we can just put it in the header of the other page.

Personnally I would put it on the main page, if people who can't come to LHDs think it's too much spam they can always follow elsewhere and get the same/similar info, right?

-Francesca

**Comment by SolalPirelli** [comment]
Thanks for the suggestions!

**Comment by SolalPirelli** [comment]
Home page now links to LauzHack Days, in the red description section.
