### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by SolalPirelli** [LauzHack/LauzHack.github.io#8]
GitHub Pages recently allowed HTTPS, but on this repo's settings, it says "Unavailable for your site because your domain is not properly configured to support HTTPS".

[ ] Figure out what's wrong with the NameCheap config
[ ] Fix it

**Comment by RomainGehrig** [comment]
Apparently, HTTPS for custom domains was implemented very recently (I've had the problem before, with no solution available at the time): https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by SolalPirelli** [comment]
FWIW, polyprog.epfl.ch (also a GitHub Page) currently works with HTTPS, so if EPFL's IT team can do it, we can! :D

**Comment by SolalPirelli** [comment]
Done.
