### ISSUE TITLE
Migrate off Google Maps

### ISSUE THREAD

**Issue by SolalPirelli** [LauzHack/LauzHack.github.io#9]
Currently, we have a GMaps map on the website to show Lausanne's position. This is provided for free by GMaps, all we need is an API key.

However, GMaps is transitioning to a paid model where the first $200/month are free. This requires registering a credit card, which probably means if we ever get above that limit we'd automatically get billed.

We need to figure out a way to migrate to something else.

Ideas:
- Simply use a static map of Lausanne (assuming people don't need interactivity?)
- Bing Maps, Here WeGo (formerly Here Maps), OpenStreetMaps, ...?
- Don't use a map at all? Do we need it?
- ..?

- [x] Decide on an idea
- [x] Implement it

**Comment by tOverney** [comment]
Can't we take a screenshot of google maps and link that image to the coordinate on google maps?

**Comment by SolalPirelli** [comment]
We can, that's a good idea. :)

**Comment by SolalPirelli** [comment]
Done for 2018, still TODO for past websites, also need to delete tokens in the API console.

**Comment by SolalPirelli** [comment]
Done
